# Generated by Django 5.0.6 on 2024-05-10 23:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("weight", models.IntegerField(default=0)),
            ],
            options={
                "verbose_name": "Konto",
                "verbose_name_plural": "Konten",
                "ordering": ["category", "weight"],
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("weight", models.IntegerField(default=0)),
            ],
            options={
                "verbose_name": "Kategorie",
                "verbose_name_plural": "Kategorien",
                "ordering": ["weight"],
            },
        ),
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("payment_party", models.CharField(max_length=255)),
                ("banking_text", models.CharField(max_length=255)),
                ("reference", models.TextField()),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("additional_information", models.TextField(blank=True)),
                (
                    "account",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="haushaltsbuch.account",
                    ),
                ),
            ],
            options={
                "verbose_name": "Buchung",
                "verbose_name_plural": "Buchungen",
                "ordering": ["date"],
            },
        ),
        migrations.AddField(
            model_name="account",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="haushaltsbuch.category"
            ),
        ),
        migrations.CreateModel(
            name="Reserve",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("weight", models.IntegerField(default=0)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="haushaltsbuch.account",
                    ),
                ),
            ],
            options={
                "verbose_name": "Rücklage",
                "verbose_name_plural": "Rücklagen",
                "ordering": ["name"],
            },
        ),
        migrations.AlterUniqueTogether(
            name="account",
            unique_together={("category", "name")},
        ),
    ]
