# Generated by Django 5.0.6 on 2024-05-15 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("haushaltsbuch", "0003_alter_booking_account"),
    ]

    operations = [
        migrations.CreateModel(
            name="Correctures",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Ein positiver Betrag bedeutet, dass wir eine Erstattung z. B. in bar erhalten haben.",
                        max_digits=10,
                    ),
                ),
                ("description", models.TextField()),
            ],
            options={
                "verbose_name": "Korrektur",
                "verbose_name_plural": "Korrekturen",
            },
        ),
    ]
