# Generated by Django 5.0.6 on 2024-05-15 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("haushaltsbuch", "0004_correctures"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="get_from_reserve",
            field=models.BooleanField(default=False),
        ),
    ]
