# Generated by Django 5.0.6 on 2024-05-15 20:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("haushaltsbuch", "0005_booking_get_from_reserve"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="booking",
            name="get_from_reserve",
        ),
        migrations.RemoveField(
            model_name="reserve",
            name="account",
        ),
        migrations.AddField(
            model_name="booking",
            name="reserve",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="bookings",
                to="haushaltsbuch.reserve",
            ),
        ),
    ]
