# Generated by Django 5.0.6 on 2024-05-15 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("haushaltsbuch", "0006_remove_booking_get_from_reserve_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Correctures",
            new_name="Correcture",
        ),
    ]
